# Generated by Django 2.1.7 on 2019-07-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delete',
        ),
    ]
